services:
  # Our PostgreSQL  databse
  db:
    # The Docker image of postgres -- we're using the latest.
    image: postgres:latest
    # The ports to expose to the host container
    # 5432 is the default PostgreSQL port
    ports:
      - '5432:5432'
    # if we accidentally kill the running container, DOcker Compose
    # will restart it.
    restart: always
    # The PostgreSQL Docker container uses environment variables to
    # read configuration, here we set the password.
    # ⚠️ - Do not store plaintext passwords in source control. We
    #      do so here as this is a builder
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
